# Generated by Django 3.1.7 on 2021-12-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211206_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fierro', 'Fierro'), ('Cemento', 'Cemento'), ('Ladrillo', 'Ladrillo')], max_length=50, null=True),
        ),
    ]
